### ISSUE TITLE
Bug: OK-Button bleibt grau

### ISSUE THREAD

**Issue by madmaxjuno** [ds10git/hibiscus.splittransaction#1]
Plugin hibiscus.splittransaction Version 0.3.0
Bereits direkt nach dem Aufrufen des Fensters "Umsatz aufsplitten" erscheint der Button "OK" ausgegraut und der Umsatz lässt sich nicht aufsplitten, egal welche Eingaben in dem Fenster gemacht werden, egal ob die Option "Beträge automatisch neu berechnen" aktiviert ist oder nicht.
Dies tritt wiederholt auf. Die meisten Umsätze lassen sich erfolgreich aufsplitten, bei dem Rest funktioniert es wie oben beschrieben auch nach vielfachen Versuchen nicht.
Das Problem tritt zwar mit Version 0.3.0 seltener auf als in Version 0.1.0, besteht aber grundsätzlich immer noch.
Kann ich noch irgendwelche Angaben machen, die zum Fixen beitragen?

**Comment by ds10git** [comment]
Der Beschreibung nach zur urteilen, ist in den Fällen, in denen der Button ausgegraut ist, der Betrag des Original-Umsatzes bereits mit einer Abweichung vom vollen Cent-Betrag versehen, dann wird der OK-Button bisher nicht mehr aktiviert, da es nie zur Übereinstimmung der Beträge kommt. Ich habe jetzt ein Update hochgeladen, der den Orinial-Betrag auf volle Cent-Beträge rundet, damit sollte das Problem nicht mehr auftreten. Bei der alten Version müsste der OK-Button theoretisch dann aktiviert werden, wenn der addierte Betrag der aufgeteilten Umsätze einen Cent niedriger ist, als für den Betrag des originalen Umsatzes angezeigt wird.

**Comment by madmaxjuno** [comment]
Mit der Version 0.3.2 konnte der Original-Betrag erfolgreich aufgeteilt werden. Vielen Dank für den promten Fix.
