### ISSUE TITLE
Umsatz-Kategorie-Feldlänge

### ISSUE THREAD

**Issue by madmaxjuno** [ds10git/hibiscus.splittransaction#3]
Könnten Sie bitte das Umsatz-Kategorie-Feld länger definieren, damit auch etwas längere oder Unterkategorien vollständig lesbar sind.
Danke
![Umsatz aufsplitten, Umsatz-Kategorie-Feld zu kurz](https://github.com/ds10git/hibiscus.splittransaction/assets/102965105/5977dd88-9e81-4edf-b414-840642892ab5)

**Comment by ds10git** [comment]
Das sieht nach einem Fehler im System aus. Die Auswahl der Kategorie sollte den Rest der zur Verfügung stehenden Breite ausfüllen. Das wird von Jameica so gehandhabt und darüber hat ein Plugin auch keine direkte Kontrolle.
